### PR TITLE
[#244] Require only one healthy server

### PR DESCRIPTION
**Pull request by KirillovDenis**
There are some problems with  `nspccdev/neofs-aio-testcontainer:0.27.5`

Signed-off-by: Denis Kirillov <d.kirillov@yadro.com>

### CODE REVIEW

**Review by roman-khimov — CHANGES_REQUESTED** [review]
I guess it's very similar to nspcc-dev/neo-go#2878, you have a broken configuration and you want it to partially work. I do believe it's much friendlier behavior for ops to have things like this _fail fast_ instead of hiding the problem (or problems, there is a number of ways for this to break). If you need to work with one interface temporarily --- adjust the config.

**Comment by alexvanin** [comment]
> I guess it's very similar to [nspcc-dev/neo-go#2878](https://github.com/nspcc-dev/neo-go/issues/2878), you have a broken configuration and you want it to partially work. I do believe it's much friendlier behavior for ops to have things like this _fail fast_ instead of hiding the problem (or problems, there is a number of ways for this to break). If you need to work with one interface temporarily --- adjust the config.

Agree with that. However we have different behavior for `pool` and `server` sections. `pool` requires at least one valid endpoint to start, so `server` is expected to behave the same. And `warn` logs might be good enough to notify admin something is going wrong, in my opinion.

**Comment by roman-khimov** [comment]
> However we have different behavior for pool and server sections.

And that's OK, these are completely different areas of responsibility, pool nodes are 3rd party things gateway can't control. While it certainly is the gateway responsibility to correctly bind to all of the required (specified in the configuration) addresses.

Take `nginx` for example, it has `listen` and it has `proxy_pass`, I think it handles them in a bit different way wrt similar problems.

**Comment by realloc** [comment]
nginx reference is irrelevant here. Interfaces come and go. The desired behaviour for the http-gw is not fail fast, but to live in a degraded environment.

**Comment by roman-khimov** [comment]
> nginx reference is irrelevant

It's very much relevant. Of course there are many ways to handle this and there are lots of various services on this planet (up to `dnsmasq`), but I think the majority of them behave this way. I'd try to minimize surprising ops people. Right now it's all fair and simple, broken config -> service doesn't start -> fix the config. The "service doesn't start" part is a very user-friendly thing here, it's immediately visible, unlike something in logs.

> Interfaces come and go

Yep, and current PR doesn't handle this situation at all.

> to live in a degraded environment

Except this PR doesn't allow the service to do that, see examples in nspcc-dev/neo-go#2878, it will just silently break.

If we're to have truly dynamic behavior here with the service handling IPs coming and going (binding to appropriate IPs, but this has to work on every platform), that can be an option (not worth the trouble IMO, but can be). This PR as it is now certainly not.

**Comment by alexvanin** [comment]
Having multiple server endpoints might improve fault-tolerance when some interfaces might go down while sever accidentally restarts. It would be nice to keep gateway service alive in this case, because straight away reconfiguration might not be possible in isolated environments.

@roman-khimov, what you think about:
1) keeping PR in support branch and not porting it to master branch,
2) adding a feature flag to enable described behavior in this PR?

**Comment by roman-khimov** [comment]
> keeping PR in support branch and not porting it to master branch,

It affects behavior and support branches are supposed to have some releases. We want to have unified behavior in all releases (except of course support branches might miss some new functionality from the `master). Also, we may have `support/X`, then there'll be `support/Y` and so on, keeping this patch in all of the branches, but avoiding adding it to `master` would look somewhat strange.

> adding a feature flag to enable described behavior in this PR?

RedundantAddresses=true/false with the `false` default? It can make this PR acceptable, but judging from nspcc-dev/neo-go#2878 it's just a test issue and not a real problem. Also, this behavior has some side-effects described in the same issue, I don't know when and where but it will bite you in future. So I'd recommend not doing it at all.

**Pull request closed without merging**
